### PR TITLE
check

### PR DESCRIPTION
**Pull request by vistamou**
check

### CODE REVIEW

**Comment by dan-zeman** [comment]
The Greek documentation belongs to the folder `_el` (https://github.com/UniversalDependencies/docs/tree/pages-source/_el). Please do not duplicate it in `el`.

Also, note that individual part-of-speech categories have their pages in `_el/pos`, and dependency relations in `_el/dep`. So perhaps the page `el/dep.md` should be merged with either `_el/dep/det.md` or `_el/pos/DET.md`?

**Comment by stellamarks** [comment]
Dear Dan

please accept my wishes for the New Year.

It was actually a question of mine. My group is working on a Greek  corpus
(I will call it Corpus2) that is different from the one that is already
uploaded for Greek (I will call it Corpus1). The approach to morphological
annotation adopted in Corpus2 is somewhat different from the one adopted in
Corpus1; in fact, I would say that Corpus1 is morphologically closer to
UD.V1 and Corpus2 closer to UD.V2. In addition, we add some new
morphological features concerning degree modification which is a very
popular morphological (and syntactic) phenomenon in Greek---at least,
degree modification morphology is explicit and uncontroversial. In short,
the guidelines I have put in "el" do not apply to the corpus that is
related to "_el". Furthermore, there are practically no morphological
guidelines for Corpus1 (the corpus related with _el).

We are currently working on Corpus2 and we plan to upload it in March 2022.
I was planning to send an email with these questions at that time but your
email arrived earlier --- thanks for that!

So, given this situation, please instruct me how to proceed.

Thanks indeed for your time and your cooperation.

Wishes for health.

Stella

**Comment by dan-zeman** [comment]
Hi Stella (note that this thread is not e-mail-only, in fact it is still the Github discussion at https://github.com/UniversalDependencies/docs/pull/829), the UD policy is that there is one set of language-specific guidelines per language, and all treebanks of that language adhere to those guidelines. When there are multiple teams working on different treebanks, ideally they should communicate and arrive at a consensus.

Sometimes it is difficult to reach this ideal state, and there are minor differences between treebanks in other languages, too. It is desirable to document treebank-specific differences at places where the related guideline is discussed. In any case such differences should be minimized, as people may want to train one model on a union of treebanks, and it is not possible if the treebanks differ substantially. It does not necessarily mean that a newer treebank is doomed to stick with suboptimal decisions taken by someone else. But some effort should be made to persuade the providers of the older treebank to adjust their data so that both treebanks are improved.

**Comment by stellamarks** [comment]
Καλημέρα (goodmorning) Dan



On Mon, Jan 3, 2022 at 2:53 PM Dan Zeman ***@***.***> wrote:

> Hi Stella (note that this thread is not e-mail-only, in fact it is still
> the Github discussion at #829
> <https://github.com/UniversalDependencies/docs/pull/829>), the UD policy
> is that there is one set of language-specific guidelines per language, and
> all treebanks of that language adhere to those guidelines. When there are
> multiple teams working on different treebanks, ideally they should
> communicate and arrive at a consensus.
>
> Sometimes it is difficult to reach this ideal state, and there are minor
> differences between treebanks in other languages, too. It is desirable to
> document treebank-specific differences at places where the related
> guideline is discussed. In any case such differences should be minimized,
> as people may want to train one model on a union of treebanks, and it is
> not possible if the treebanks differ substantially. It does not necessarily
> mean that a newer treebank is doomed to stick with suboptimal decisions
> taken by someone else. But some effort should be made to persuade the
> providers of the older treebank to adjust their data so that both treebanks
> are improved.
>
> —
>
I have emailed the group who have developed the other Greek treebank and
asked them if my group can modify their POS annotation (and whether we
could discuss the guidelines proposed by the two groups). I will let you
know about the results of the negotiations and you will instruct me
accordingly.

Thank you very much for your time and your help.

Please accept my wishes for health.

Cheers

S

**Pull request merged**
