### PR TITLE
Update CONJ.md

### PR DESCRIPTION
**Pull request by aliya1303**
Updated grammar about coordinating conjunctions in Kazakh.

### CODE REVIEW

**Comment by ftyers** [comment]
Hi there @aliya1303! Thanks for your contribution :) 

We will take a look through your suggestions and get back to you asap. In the mean time, are "бірдс", and "брлмаса" typos ?

**Comment by jonorthwash** [comment]
Hi @aliya1303!

We were wondering if you could finish adding examples for all the types of conjunctions, and saying which are coordinating and which are subordinating.  It would make for a more complete pull request.

Also, some other potential typos: "үй да", "брла", "жылынбалы".  Make sure to double-check any other Kazakh examples you submit.

**Comment by aliya1303** [comment]
Good day! I have changed document adding more examples and correcting some sentences. Information in this CONJ document is about coordinating conjuctions and general overview of conjuctions in Kazakh. Information about subordinating conjunctions i have added into SCONJ document. Also in SCONJ document general overview of conjuctions in Kazakh presented too.
Thank you!

**Comment by dan-zeman** [comment]
Closing as it does not match the current file-folder structure.

**Pull request closed without merging**
