### PR TITLE
Update punct.md

### PR DESCRIPTION
**Pull request by Binyamephrem**

### CODE REVIEW

**Comment by Binyamephrem** [comment]
If there are two or more objects, one of them should be obj and the others should be iobj.

**Comment by martinpopel** [comment]
Thanks

**Comment by Binyamephrem** [comment]
This case is similar to example number 47, 63 and 148.

**Comment by martinpopel** [comment]
> This case is similar to example number 47, 63 and 148.

I don't know where are these examples 47, 63 and 148. (Each page numbers the examples from 1 and the numbers are not stored in the source code.)
Nevertheless, I have converted all `dobj` to `obj` in the universal part of the guidelines (except for legacy v1 pages):
https://github.com/UniversalDependencies/docs/commit/eb4de005f74

**Comment by Binyamephrem** [comment]
The numbers appear in the documentation. In the documentation every example
has number. That is what I was referring. But now all are changed.

**Pull request merged**
