### PR TITLE
Update introduction.md

### PR DESCRIPTION
**Pull request by matswiren**

### CODE REVIEW

**Comment by arademaker** [comment]
Hi, the documentation should be focus on a specific treebank or it should be more related with UD for that language? The first paragraph is making the document very specific for the treebank.

**Comment by robertostling** [comment]
@arademaker As far as I can see the other languages also include general information about treebank construction, data sources, etc. The UD-specific parts are forthcoming, we are currently translating that material from Swedish.

**Comment by dan-zeman** [comment]
Yes, introduction to language-specific documentation is always more about the treebank(s) than about the language. If there are multiple treebanks for the language, there should be a section for each.

**Comment by arademaker** [comment]
@dan-zeman ok for the introduction.md file and maybe for other general pages but what about the specific pages? For example

http://universaldependencies.org/pt/dep/acl-relcl.html

We have recently instantiate the Portuguese version of this page but the stats are still showing the numbers from the UD_Portuguese-BR corpus only.

**Comment by dan-zeman** [comment]
Pages about a tag / feature / relation should be generally valid for the language. If there are any divergences in a particular treebank, there should be a diff section at the end _of the manually written part._

The treebank statistics are a different story. They are generated by a script, typically at release time. Unless I run the script manually at some other point in time, they reflect the data from the last official release. I do not think the `acl:relcl` relation appears anywhere in UD_Portuguese, or does it? Then no statistics for this label have been collected and generated.

**Comment by arademaker** [comment]
@dan-zeman they do in your new version of this corpus at http://github.com/own-pt/bosque-UD/

```
$ grep acl:relcl bosque_C*conll | wc -l
    2487
```

I am assuming the stats are about all the corpora of the language, right?

**Comment by dan-zeman** [comment]
OK, you score :-) I did not have time to check the data. So it should appear at the page when compiling the next release. Let me know if it does not.

**Pull request merged**
