### PR TITLE
Exemplify word delimitation through Japanese

### LINKED ISSUE #946: New seg. docs and closed class property of tags
The new segmentation document found at https://github.com/UniversalDependencies/docs/blob/pages-source/workgroups/newdoc/word_segmentation.md makes essential clarifications, particularly for languages that either lack spelling rules about explicit breaks or have under-defined rules.

While the document states,

> If there is no suitable UPOS tag for the surface token, but we can split it into parts that have clear UPOS categories, split it

I would like to kindly ask about the potential of an update to address the closed-class property of a UPOS tag as a suitability differentiator.

Would it be possible to specifically mention that if splitting a word maintains the closed class property of a UPOS tag, then it is considered suitable for splitting? Guidelining such a distinction would help ultimately resolve issues related to certain particles or affixes in languages like Turkish, such as the "-s[ae]" conditional, resolving the topic of producing the open class SCONJ, and I believe it would generalize really well to not only Turkic but also languages with similar concerns. I also think that it is better to encourage multi-word tokens in such cases to preserve the original spelling.

### PR DESCRIPTION
**Pull request by mehmetoguzderin**
Closes https://github.com/UniversalDependencies/docs/issues/946

I would like to kindly PR the addition of a paragraph to the new tokenization and segmentation document, which aims to illustrate the challenges associated with identifying word boundaries in languages with complex morphological structures, such as agglutinative languages where boundaries can be problematic regarding promoting dependent morphemes into syntactic words. I am eager to receive feedback and will promptly make revisions if prompted to ensure the text balances clarity and intricacy.

> Another example involves particles, affixes, or clitics in agglutinative languages like Japanese: _やめれば = やめれ + ば._ Such languages may lack (e.g., Japanese) or have inconsistent (e.g., Old Turkish ":" separator) orthographic word delimiters. In the context of Japanese, the preferred split in UD separates _やめれ_ into VERB and _<b>ば</b>_ into SCONJ, producing a closed class for SCONJ, i.e., having an enumerable number of SCONJ lemmas independent of the set size of NOUN or VERB tags (contrast making such cases a morphological feature: SCONJ tag would be absent). By splitting, we allow covering more UPOS tags and deeper syntax trees for cross-linguistic alignment without violating open-closed categories, even without standard syntactic word delimitation.

Although some might perceive the proposed short paragraph as a redundant and verbose addition, I firmly believe that including this example is essential for helping readers to understand better the intricacies found in agglutinative languages, particularly those who may not have training in linguistics terminology in the English language, highlighting the critical importance of recognizing open-closed category distinctions, otherwise easily overlooked but is vital for a comprehensive understanding of the topic for a correct evaluation.

Last but not least, this exemplification reflects the status quo as found directly in a language with a well-working instance of this, and the document is already about giving a helping hand to people for ease of understanding. I would really appreciate the support to incorporate this addition as a person who had a lot of learning from the Universal Dependencies project.

### CODE REVIEW

**Review by dan-zeman — CHANGES_REQUESTED** [review]
As I said in #946, I don't want a Japanese example in the section about multiword tokens because it would be confusing for the reader: we don't use MWTs in Japanese, and it is even stated clearly earlier on the same page.

Even if it were not Japanese, I believe that the claims in the paragraph are wrong. The grammatical morpheme in question is considered a word by the annotators, as such it needs an UPOS tag, and it gets a closed-class one, `SCONJ`. That's fine if the morpheme really deserves to be a syntactic word, but it itself is not _the evidence_ that the morpheme should be a word. If it were not a word, then it would be an affix which turns the verb into a subordinate form, which is also a completely legitimate analysis cross-linguistically. It would still be closed class, because affixes are closed class by definition; only it would not get the UPOS tag because those are only awarded to words. So I think this line of argumentation should not be there, regardless whether it is exemplified with Japanese or with any other language.

**Comment by mehmetoguzderin** [comment]
@dan-zeman TBH, the proposed PR's text streamlined the reasoning for that (why not affix as morphological inflection): if otherwise a language does not produce a UPOS, then split into syntactic words. This fact holds, especially for historical attestations of these languages. And furthermore, if producing a closed class and a UPOS otherwise missing are not enough evidence, then why not make everything NOUN and VERB in these languages in UD (there are such analyses of the derivations of these languages, certainly not absurd, but the context of UD has better options for cross-linguistic alignment)? For me, these considerations were the explaining reasoning as to why not the hypothetical case.

Although I'd really like to iterate on the location of text to reduce confusion while keeping the benefit, dialogue circles just skip over the intention entirely. Hence I closed. Apologies for taking the time with my inquiry.

**Comment by dan-zeman** [comment]
You are absolutely right that we don't want to end up with just nouns and verbs in all languages, and I'm partly sorry for being so resistant to your proposals, but I think it's very difficult to identify criteria that work in all languages. Hence I try to be careful about introducing guidelines that could be misleading or confusing. There is always danger that people will apply them in other languages or in ways that may not be appropriate. Specifically for closed-class function words vs. affixes, I think we don't have to prefer one of them at the expense of the other, because you can always use the UD features to annotate the contribution of affixes. But if there is evidence that in the given language the same morpheme is actually used as an independent word, then of course it makes sense to cut it off also in situations where it is spelled together with a neighboring word.

**Comment by mehmetoguzderin** [comment]
@dan-zeman Thank you for your valuable insights, and I understand the concerns about ensuring the guidelines have proper application across different languages. I believe we have always been on the same page, more or less. It's important to have a principled approach to split or affix in these vaguer (due to history or whatever, just not enough directly applicable specification in certain languages' linguistics) territories. I never meant my proposal as the last and final place, and I believe the main miscommunication is happening in the iteration of guideline suggestions to pluralize and diversify contributions. For contributing to tools and code in the Universal Dependencies project, it is always quite a gentle process since it either executes per intention or fixes a bug. A library dependency error is easy to point out. But here, it feels like despite the intention being a draft to iterate together to include an extra voice, not in a clash of guidelines or data, the gradient feels totally missing.

For the dangers, I only see a step forward with such clarification compared to existing issues in datasets. By reminding of basic driving principles which pick segmentation in these languages as producing word classes for UD-suitable framing, it can be a reminder for annotators to fix.

**Pull request closed without merging**
